nombre: Balanceada

descripcion: Estrategia equilibrada.

version: 1.0
score:

  sc20:
    peso: 0.30

  sc50:
    peso: 0.25

  sc100:
    peso: 0.20

  atraso_norm:
    peso: 0.10

  hist_ap_norm:
    peso: 0.15

  tendencia20_100:
    peso: 0.00
    
plugins:

  promedio:

    activo: true
    orden: 10

    parametros:

      ap20: 0.60
      au20: 0.40

      ap50: 0.60
      au50: 0.40

      ap100: 0.60
      au100: 0.40

  normalizacion:

    activo: true
    orden: 15
    parametros: {}

  tendencia:

    activo: true
    orden: 18
    parametros: {}

  atraso:

    activo: true
    orden: 20

    parametros:

      dias_minimos: 8


rules:

  pares:

    activo: true

    parametros:

      minimo: 2
      maximo: 4

  bajos:

    activo: true

    parametros:

      minimo: 2
      maximo: 4

  suma:

    activo: true

    parametros:

      minimo: 60
      maximo: 180

  decadas:

    activo: true

    parametros:

      minimo: 3
      maximo: 5

  categoria:

    activo: true

    parametros: {}

generator:

  tipo: weighted

  parametros:

    cantidad: 20